### PR TITLE
Added constructor definitions.

### PR DESCRIPTION
**Pull request by Fyorl**
Sometimes in my test code I need to extend discord.js classes and override their constructors which is impossible without the constructor definitions.

### CODE REVIEW

**Comment by zajrik** [comment]
Until the currently in-development Typescript release that overhauls Object is released, you'll want to use `any` to represent an object without any explicitly defined fields. There's a few formatting changes I see need to be made as well but I'm on mobile. I'll take care of them when I get on next, but if you could convert all of your uses of `Object` to `any`, that would be very helpful.

**Comment by zajrik** [comment]
I was mistaken on the `Object` overhaul in TS 2.2. It's actually introducing a new `object` type to which primitives are not assignable. This will serve the purpose of `any` for places where an object without explicitly defined fields is desired without allowing literally everything else as well going forward with the typings.

Didn't want to leave that misinformation here all day. Going to go to sleep and finish reviewing this after I wake up.

**Comment by Fyorl** [comment]
thanks for the quick review and merge

**Comment by zajrik** [comment]
No problem. Thanks for your contribution :D

**Pull request merged**
