### PR TITLE
attachmentclass + messageembed fix

### PR DESCRIPTION
**Pull request by Lewdcario**
Typings for my last PR, Attachment, and updating MessageEmbed typings that were missing for the methods.

### CODE REVIEW

**Comment by zajrik** [comment]
I haven't looked at your pr yet. Is it for v12 or is it for 11.1-dev? At this point we are not quite yet working on v12 typings so I want to make sure.

**Comment by Lewdcario** [comment]
its for the master branch, if attachments gets accepted. sorry for not making that obvious!

**Comment by zajrik** [comment]
No problem. Going forward, please specify which branch the pr is for that your typings additions cover if you make any other prs. Until we start on v12 typings I'll leave this pr open. Feel free to modify the pr further if you make changes to the code you're adding to d.js master.

**Comment by PgBiel** [comment]
Shouldn't this remove RichEmbed?

**Comment by PgBiel** [comment]
Also, you only added Attachment class without actually implementing it in the methods. Please do so.

I also highly recommend you add a generic for the used file type so you don't have to keep repeating yourself.

**Pull request closed without merging**
